name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Comment APSS link on workflow"
        uses: trungleduc/appsharingspace-pr-comment/.github/actions/pr-comment@main
        with:
          github_token: ${{ secrets.github_token }}
          artifact_name: artifact
          index_path: lab/index.html